// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jphrigjjofkmghpwurwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwaHJpZ2pqb2ZrbWdocHd1cndkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTgxOTEsImV4cCI6MjA2NDE3NDE5MX0.lSW-lJZ_eG1HlgPGEnNHUCKVQdbG2J4RLVvd44rnZk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);